### ISSUE TITLE
Installation instruction does not work

### ISSUE THREAD

**Issue by ganesh-at-wiw** [GluuFederation/roundcube_oxd_plugin#6]
$ composer install `composer require "GluuFederation/roundcube-oxd-plugin": "2.4.4"`

Does not work.

**Comment by ganesh-at-wiw** [comment]
The composer.json in roundcube root folder should look like:


    "require": {
        "php": ">=5.3.7",
        "pear/pear-core-minimal": "~1.10.1",
        "roundcube/plugin-installer": "~0.1.6",
        "pear-pear.php.net/net_socket": "~1.0.12",
        "pear-pear.php.net/auth_sasl": "~1.0.6",
        "pear-pear.php.net/net_idna2": "~0.1.1",
        "pear-pear.php.net/mail_mime": "~1.10.0",
        "pear-pear.php.net/net_smtp": "~1.7.1",
        "pear-pear.php.net/crypt_gpg": "~1.4.2",
        "roundcube/net_sieve": "~1.5.0",
        **"gluufederation/roundcube-oxd-plugin": "2.4.4"**
    },

Then we need to run:

> composer install

**Comment by dollar007** [comment]
it is not needed, admin can install plugin without other packages

**Comment by dollar007** [comment]
it is not needed, admin can install plugin without other packages, but I have added
