### ISSUE TITLE
The OpenID plugin is not listed in roundcube settings even after installation

### ISSUE THREAD

**Issue by ganesh-at-wiw** [GluuFederation/roundcube_oxd_plugin#7]
The openid plugin is not listed in roundcube settings even after installation.

The root cause is: **rcube_oc_sso_plugin_by_gluu.php**  file.
The file should be renamed as: **roundcube_oxd_plugin.php**.

Also, all occurrences of the word:  **rcube_oc_sso_plugin_by_gluu** should be changed to **roundcube_oxd_plugin**.

Please correct it.

**Comment by dollar007** [comment]
Done
